### PR TITLE
Support page header setting of changelog file

### PR DESCRIPTION
**Pull request by lpreterite**
# Why this PR

Because I need to add more custom descriptions to the header of the CHANGELOG file .

It is the same as the [conventional-changelog-config-spec](https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.1.0/README.md#header-string) setting of [standard-version](https://github.com/conventional-changelog/standard-version/blob/master/lib/lifecycles/changelog.js#L51).

# What this PR fix

Increase in the configuration header is provided, at its head and applied to the document output. 

# Configuration samples

```json
{
  "plugins": {
    "@release-it/conventional-changelog": {
      "infile": "CHANGELOG.md",
      "header": "# 📋 更新历史 \n\n",
      "preset": {
        "name": "conventionalcommits"
      }
    }
  }
}
```

### CODE REVIEW

**Comment by webpro** [comment]
The options are sent to the plugin, so I would expect you could use any of those options. You would need to move the header property into the `preset`.

Please see https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.1.0/README.md

I've just updated the docs with this, so thanks for raising the issue and opening this PR!

**Comment by lpreterite** [comment]
# Hope to review this PR again 

I want to explain two things:
1. The header set in the preset does not take effect
2. After passing the header settings to the plug-in during the local debugging process, the results obtained are far from expected.

## Expect
The header is only at the top of the page

```md
# Changelog

This document lists breaking changes for each major release.

See the GitHub Releases page for detailed changelogs:
[https://github.com/release-it/release-it/releases](https://github.com/release-it/release-it/releases)

## v14

- Removed `global` property from plugins. Use `this.config[key]` instead.
- Removed deprecated `npm.access` option. Set this in `package.json` instead.

## v13

- Dropped support for Node v8
- Dropped support for GitLab v11.6 and lower.
- Deprecated `scripts` are removed (in favor of [hooks](https://github.com/release-it/release-it#hooks)).
- Removed deprecated `--non-interactive` (`-n`) argument. Use `--ci` instead.
- Removed old `%s` and `[REV_RANGE]` syntax in command substitutions. Use `${version}` and `${latestTag}` instead.

```

## Reality
The header will appear in the top of each version of content changes
```md
# Changelog

This document lists breaking changes for each major release.

See the GitHub Releases page for detailed changelogs:
[https://github.com/release-it/release-it/releases](https://github.com/release-it/release-it/releases)

## v14

- Removed `global` property from plugins. Use `this.config[key]` instead.
- Removed deprecated `npm.access` option. Set this in `package.json` instead.

# Changelog

This document lists breaking changes for each major release.

See the GitHub Releases page for detailed changelogs:
[https://github.com/release-it/release-it/releases](https://github.com/release-it/release-it/releases)

## v13

- Dropped support for Node v8
- Dropped support for GitLab v11.6 and lower.
- Deprecated `scripts` are removed (in favor of [hooks](https://github.com/release-it/release-it#hooks)).
- Removed deprecated `--non-interactive` (`-n`) argument. Use `--ci` instead.
- Removed old `%s` and `[REV_RANGE]` syntax in command substitutions. Use `${version}` and `${latestTag}` instead.

```

**Comment by dangreen** [comment]
@webpro Hi. Why you closed this PR? This feature is very wanted. standard-version also have this logic on its side

https://github.com/conventional-changelog/standard-version/blob/fb3f3fa7b7ea999b5ef714acc780b3c265caac63/lib/lifecycles/changelog.js#L50

**Comment by webpro** [comment]
My apologies for understanding the issue incorrectly. Can someone please pick up this PR and also fix and add one or more tests please?

GitHub says I can't re-open this PR, so please open a new one. I'll be happy to review and merge this feature.

**Pull request closed without merging**
