### PR TITLE
chore: bump use caret to get `semver` minor version, fixes #67

### LINKED ISSUE #67: semver version should be bumped to fix CVE
I saw that `semver` is using a fixed version in the `package.json`, I think that was maybe a typo that stayed in the code for a long time. It should probably be using the caret prefix as `^7.5.3`, see

https://github.com/release-it/conventional-changelog/blob/7c90551bf556c479e1a40b79609b1f500fb8bee6/package.json#L40

and this would partially fix the following CVE issue

> @release-it/conventional-changelog@7.0.0 requires semver@7.5.1

> Versions of the package semver before 7.5.2 on the 7.x branch, before 6.3.1 on the 6.x branch, and all other versions before 5.7.2 are vulnerable to Regular Expression Denial of Service (ReDoS) via the function new Range, when untrusted user data is provided as a range.

Please note that this **will not fix** all `semver` issues since `conventional-changelog-core` is pointing to an old `semver` version via a transitive dependency of `read-pkg@3.0.0` as I pointed out in this conventional-changelog issue [comment](https://github.com/conventional-changelog/conventional-changelog/issues/1019#issuecomment-1644110023). It's probably going to take a long while since maintenance on that project are moving at a rather slow pace.

Until conventional-changelog team release a fix, I use a simple yarn resolution in the meantime
```js
"resolutions": {
    "semver": "^7.5.4"
},
```

### PR DESCRIPTION
**Pull request by ghiscoding**
- I'm not sure why it was using a fixed version, but I assumed it was a possible typo or an old fix and we should be good to update
- fixes #67

### CODE REVIEW

**Comment by ghiscoding** [comment]
@webpro not sure if you've seen the PR in your queue, so just pining you :)

**Comment by webpro** [comment]
A test failed when updating `semver`, since `conventional-changelog` uses an older version of `semver`. Guess we'll have to wait for a fix upstream.

**Comment by lightness** [comment]
@webpro 
Looks like, it was intentional change. Take a look [here](https://github.com/npm/node-semver/pull/566/files#diff-8a30a1d4287907e0b148df70a2cad3c6758d29c24027f9358c066628db66bcddR23)

From my perspective it looks kinda strange to name diff like `1.0.0-1` => `1.0.0` MAJOR 🤯 . And they perform such breaking change in patch version (7.5.2)... Semver doesn't follow itself? 🤔 

But we should somehow fix vulnerability.

Can we adjust test for new reality?

**Comment by webpro** [comment]
I've had to fix a few more things, but this is now in [v7.0.1](https://github.com/release-it/conventional-changelog/releases/tag/7.0.1). Thanks everyone :)

**Comment by ghiscoding** [comment]
Awesome, thanks @webpro for taking this over, I just came back from vacations :)

**Comment by webpro** [comment]
No worries I waited

**Pull request closed without merging**
