### PR TITLE
fix: ignoreRecommendedBump

### PR DESCRIPTION
**Pull request by txp1035**
It should be disabled if ignored
I think your logic is backwards  @webpro

### CODE REVIEW

**Comment by webpro** [comment]
Had to think it through a few times, but I still think it is correct already:

- The `version` plugin should be disabled when we want to use the recommended bump (default).
- The `version` plugin should be enabled when we want to ignore the recommended bump.

Hence:

- When `ignoreRecommendedBump: false` (default) this `disablePlugin` should return `version` to disable the `version` plugin. By default this plugin disables the `version` plugin and recommends a version itself (based on commits).
- When `ignoreRecommendedBump: true` this `disablePlugin` should return `null` to keep the `version` plugin enabled. To override the default behavior and **not** disable the `version` plugin, and ignore the recommended bump.

**Comment by webpro** [comment]
By the way, this is also covered by a test: https://github.com/release-it/conventional-changelog/blob/9aecd6a216578a2f4767005ecd1ae80e64e1d5c8/test.js#L140-L148

**Comment by txp1035** [comment]
> 不得不考虑几次，但我仍然认为它已经是正确的：
> 
> * `version`当我们想要使用推荐的凹凸（默认）时，应该禁用该插件。
> * `version`当我们想忽略推荐的凹凸时，应该启用该插件。
> 
> 因此：
> 
> * 当`ignoreRecommendedBump: false`（默认）这`disablePlugin`应该返回`version`禁用`version`插件。默认情况下，此插件禁用`version`插件并推荐一个版本本身（基于提交）。
> * 当`ignoreRecommendedBump: true`这`disablePlugin`应该返回`null`以保持`version`插件启用时。覆盖默认行为**而不**禁用`version`插件，并忽略推荐的凹凸。

Let me tell you the background of this PR.
If I only use release-it, there will be version selection. But when I installed the release-it/conventional-changelog plugin, version selection was not possible. This default setting gave me a headache, and finally found a solution through the source code.
The name ignoreRecommendedBump makes me mistakenly think that the version plugin is supported by default

**Comment by webpro** [comment]
Version selection is disabled, because conventional-changelog determines the bump based on the changelog. That's why the "version selection" is disabled, since release-it follows the recommended bump when this plugin is used. This is the default behavior. This can be overridden by saying "ignore recommended bump".

**Comment by txp1035** [comment]
> 版本选择被禁用，因为 conventional-changelog 根据 changelog 确定 bump。这就是禁用“版本选择”的原因，因为在使用此插件时发布时它遵循推荐的 bump。这是默认行为。这可以通过说“忽略推荐的颠簸”来覆盖。

I see. When I I turned on release, I often had some problems. Is this the reason?Like the following issues
https://github.com/release-it/release-it/issues/968

**Pull request closed without merging**
